version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: planes-api
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: planes
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - planes-db:/var/lib/mysql

volumes:
  planes-db:
